drop table mydb.EMPLOYEE;
delete from MYDB.EMPLOYEE where ENAME = 'hanuma';
delete from MYDB.EMPLOYEEDETAILS where LOCATION ='kishkinda';
select * from mydb.EMPLOYEEDETAILS
create table mydb.employee (EID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) , ENAME VARCHAR(30) NOT NULL);
create table mydb.employeedetails (EID BIGINT UNIQUE NOT NULL, FOREIGN KEY (EID) REFERENCES mydb.EMPLOYEE(EID), LOCATION VARCHAR(30) NOT NULL);
INSERT INTO MYDB.EMPLOYEEDETAILS VALUES (1,'ayodya')
INSERT INTO MYDB.EMPLOYEEDETAILS VALUES (2,'midhila')

INSERT INTO MYDB.EMPLOYEE (DOJ) VALUES ('seeta');


update mydb.EMPLOYEEDETAILS set DOJ = CURRENT_DATE

alter table mydb.EMPLOYEEDETAILS ADD DOJ DATE;

create table mydb.passport (PID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), PNO BIGINT NOT NULL);
create table mydb.Person (ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 10, INCREMENT BY 1), PID BIGINT,
FOREIGN KEY (PID) REFERENCES mydb.passport(PID));

select * from mydb.PERSON;
select * from mydb.PASSPORT;

delete from mydb.PASSPORT;


create table mydb.vehicle (VID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 100, INCREMENT BY 1), V_REGNO BIGINT NOT NULL, REG_OID BIGINT NOT NULL,
FOREIGN KEY (REG_OID) REFERENCES mydb.reg_office(OID));

drop table  mydb.vehicle;

create table mydb.reg_office (OID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 10, INCREMENT BY 1), REG_O_ID BIGINT UNIQUE NOT NULL , LOCATION VARCHAR(30) UNIQUE NOT NULL);


select * from mydb.REG_OFFICE;

select * from mydb.VEHICLE;

delete from mydb.REG_OFFICE;

ALTER TABLE mydb.passport ADD CONSTRAINT passport_pno UNIQUE (PNO);


create table mydb.Author (AID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), A_NAME VARCHAR(30) NOT NULL);

create table mydb.Book (BID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), B_NAME VARCHAR(30) NOT NULL, PUBLISH_DATE DATE NOT NULL);

create table mydb.Author_Book (AID BIGINT NOT NULL, BID BIGINT NOT NULL, PRIMARY KEY (AID,BID), 
FOREIGN KEY (AID) REFERENCES mydb.Author (AID),
FOREIGN KEY (BID) REFERENCES mydb.Book (BID));

select * from mydb.Author;

select * from mydb.Book;
select * from mydb.Author_Book;

delete from mydb.Author_Book;
delete from mydb.Author;
delete from mydb.Book;
